### ISSUE TITLE
Srt files with BOM

### ISSUE THREAD

**Issue by rwkjones** [m-lyon/filter-subs#13] opened 2022-09-26 20:42 UTC
Hi,

For some reason when I use mkvextract to pull out set files, it adds the byte order marker (BOM) to the start of the file. Subtitle filter seems to misinterpret this and removes the first subtitle. I have no idea how many other people it may affect.

Thanks,

Richard

**Comment by m-lyon** [comment] 2022-09-27 14:34
Hey Richard,

Thanks for pointing this out. Could you provide a file with the BOM present? I think I have a simple solution, but I would like to test the behaviour is correct.

Thanks

Matt

**Comment by rwkjones** [comment] 2022-09-29 11:31
[foo.txt](https://github.com/m-lyon/filter-subs/files/9674182/foo.txt)

I don't know if that will work. To check, I see the following:

$ file foo.txt
foo.txt: Unicode text, UTF-8 (with BOM) text

**Comment by m-lyon** [comment] 2022-10-01 19:48
Thanks for that, the issue is now fixed in the latest version `v1.4.4`.

**Closed by m-lyon** 2022-10-01 19:48 UTC
